In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [67]:
% matplotlib inline

In [68]:
data=pd.read_csv('assign2.csv')

In [69]:
cluster1=data[data['class']=='black']
cluster2=data[data['class']=='blue']

In [70]:
cluster1

Name  distance  diameter  density  class
0  Mercury     0.387      4878     5.42  black
1    Venus     0.723     12104     5.25  black
2    Earth     1.000     12756     5.52  black
3     Mars     1.524      6787     3.94  black

In [71]:
cluster2

Name  distance  diameter  density class
4  Jupiter     5.203    142800    1.314  blue
5   Saturn     9.539    120660    0.690  blue
6   Uranus    19.180     51118    1.290  blue
7  Neptune    30.060     49528    1.640  blue
8    Pluto    39.530      2300    2.030  blue

In [72]:
centroid1=np.array([np.mean(cluster1['distance']),np.mean(cluster1['diameter']),np.mean(cluster1['density'])])
centroid2=np.array([np.mean(cluster2['distance']),np.mean(cluster2['diameter']),np.mean(cluster2['density'])])

In [73]:
print(centroid1,centroid2)

[9.08500e-01 9.13125e+03 5.03250e+00] [2.07024e+01 7.32812e+04 1.39280e+00]


In [74]:
cl1_mat_center=np.matrix([list(cluster1['distance']-centroid1[0]),list(cluster1['diameter']-centroid1[1]),list(cluster1['density']-centroid1[2])])
cl2_mat_center=np.matrix([list(cluster2['distance']-centroid2[0]),list(cluster2['diameter']-centroid2[1]),list(cluster2['density']-centroid2[2])])

In [75]:
s1=np.dot(cl1_mat_center,cl1_mat_center.T)
s2=np.dot(cl2_mat_center,cl2_mat_center.T)

In [76]:
sw=s1+s2

In [77]:
sw

matrix([[ 8.09907386e+02, -3.13079011e+06,  2.26633834e+01],
        [-3.13079011e+06,  1.32169286e+10, -8.42719393e+04],
        [ 2.26633834e+01, -8.42719393e+04,  2.60651180e+00]])

In [78]:
sw_inv=np.linalg.inv(sw)

In [79]:
sw_inv

matrix([[ 1.54397496e-02,  3.52880863e-06, -2.01562172e-02],
        [ 3.52880863e-06,  9.01829450e-10, -1.52534364e-06],
        [-2.01562172e-02, -1.52534364e-06,  5.09594629e-01]])

In [80]:
vector=np.dot(sw_inv,centroid1-centroid2)

In [81]:
norm=np.sqrt(np.sum(np.multiply(vector,vector)))

In [82]:
norm_vector=vector/norm

In [83]:
norm_vector

matrix([[-2.49293325e-01, -5.48759768e-05,  9.68428023e-01]])

In [84]:
cl1_mat=np.matrix([list(cluster1['distance']),list(cluster1['diameter']),list(cluster1['density'])])
cl2_mat=np.matrix([list(cluster2['distance']),list(cluster2['diameter']),list(cluster2['density'])])

In [85]:
np.dot(norm_vector,cl1_mat)

matrix([[4.88471835, 4.23978922, 4.3964314 , 3.06324013]])

In [86]:
np.dot(norm_vector,cl2_mat)

matrix([[-7.86084824, -8.33112905, -6.337324  , -8.62343276, -8.01487098]])